sudo: required
services:
  - docker

install:
  - echo "${TRAVIS_BRANCH} ${TRAVIS_COMMIT}"
  - docker build -t alephdata/extract-entities:$TRAVIS_COMMIT .

script:
  # - docker run -ti alephdata/extract-entities pytest
  - sleep 1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag alephdata/extract-entities:$TRAVIS_COMMIT
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      docker tag alephdata/extract-entities:$TRAVIS_COMMIT alephdata/extract-entities:$TRAVIS_TAG ;
      docker push alephdata/extract-entities:$TRAVIS_TAG ;
    fi